name: test
ai_config:
  default_model:
    model: claude-sonnet-4-0
    provider: anthropic
  providers:
    anthropic:
      models:
        - claude-sonnet-4-0
        - claude-3-7-sonnet-20250219
      resource_path: u/alex/anthropic
    customai:
      models: []
      resource_path: u/alex/assuring_customai
auto_invite_as: developer
auto_invite_enabled: false
auto_invite_mode: invite
color: '#e22d0e'
default_app: u/alex/grateful_app
error_handler: script/hub/11598/workspace-or-schedule-error-handler-teams
error_handler_extra_args:
  channel: '19:4SkiS4RJt1gOqqwRUeXdKJvB0XoklVFX4bL9-mhPLbs1@thread.tacv2'
error_handler_muted_on_cancel: false
git_sync:
  repositories:
    - exclude_types_override: []
      git_repo_resource_path: '$res:u/alex/breathtaking_git_repository'
      group_by_folder: false
      script_path: hub/19785/sync-script-to-git-repo-windmill
      settings:
        exclude_path: []
        extra_include_path: []
        include_path:
          - f/test/**
        include_type:
          - script
          - flow
          - app
          - folder
          - resource
          - resourcetype
          - user
          - settings
          - key
      use_individual_branch: false
    - exclude_types_override: []
      git_repo_resource_path: '$res:u/alex/elated_git_repository'
      group_by_folder: false
      script_path: hub/19785/sync-script-to-git-repo-windmill
      settings:
        exclude_path: []
        extra_include_path: []
        include_path:
          - f/**
        include_type:
          - script
          - flow
          - app
          - folder
          - group
          - key
          - user
          - resource
          - trigger
          - settings
          - schedule
      use_individual_branch: true
    - exclude_types_override: []
      git_repo_resource_path: '$res:u/alex/sync_emmpty'
      group_by_folder: false
      script_path: hub/19785/sync-script-to-git-repo-windmill
      settings:
        exclude_path: []
        extra_include_path: []
        include_path:
          - f/**
        include_type:
          - script
          - flow
          - app
          - folder
          - resource
          - resourcetype
          - schedule
          - trigger
          - user
          - group
          - settings
      use_individual_branch: false
large_file_storage:
  type: S3Storage
  public_resource: false
  s3_resource_path: '$res:u/alex/local_minio'
  secondary_storage: {}
mute_critical_alerts: false
operator_settings:
  audit_logs: true
  folders: true
  groups: true
  resources: true
  runs: true
  schedules: true
  triggers: true
  variables: true
  workers: true
